name: learn-github-actions
on: [push]
jobs: 
  testpython: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: pip3 install requests unittest
      - run: python3 test_Calculator.py


