format_version: 2
pipelines:
  pipeline_code_demo:
    materials:
      backend:
        git: https://github.com/raghav1674/gocd-practice.git
        branch: master
    stages:
      - Build_Demo_Project_Stage:
          clean_workspace: true
          jobs:
            install_deps:
              tasks:
                - exec:
                    run_if: passed
                    command: pip3 
                    arguments:
                    - install -r requirements.txt
            test_app:
              tasks:
                - exec:
                    run_if: passed
                    command: python3 
                    arguments:
                    - test_Calculator.py
   